// src/components/StaggeredText.jsx
import React, { useRef, useEffect } from 'react';

const StaggeredText = ({ text, className, delay = 0, gsapLoaded }) => {
  const textRef = useRef(null);

  useEffect(() => {
    if (gsapLoaded && textRef.current && window.gsap) {
      // Ensure children are spans
      if (!textRef.current.children || textRef.current.children.length === 0 || textRef.current.children[0].tagName !== 'SPAN') {
        textRef.current.innerHTML = text.split('').map(char =>
          `<span class="inline-block">${char === ' ' ? '\u00A0' : char}</span>`
        ).join('');
      }

      const children = Array.from(textRef.current.children);
      if (children.length > 0) {
        window.gsap.fromTo(children,
          { y: 30, opacity: 0 },
          {
            y: 0,
            opacity: 1,
            duration: 0.8,
            ease: 'power3.out',
            stagger: 0.05,
            delay: delay
          }
        );
      }
    }
  }, [gsapLoaded, delay, text]);

  return (
    <div ref={textRef} className={`${className} font-heading`} aria-label={text}>
      {/* Content will be generated by useEffect */}
    </div>
  );
};

export default StaggeredText;